// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwxwhdqcvapdeczzfchs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3eHdoZHFjdmFwZGVjenpmY2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMjYwNTMsImV4cCI6MjA1MTYwMjA1M30.lgCMyooYnmEAhPkKgsPegU5OOmYr0cU2kNAxCmSnR0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);